# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CODWork/MCCPU_SOC/MCCPU_SOC.srcs/sources_1/ip/dem/dem.xci
# IP: The module: 'dem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODWork/MCCPU_SOC/MCCPU_SOC.srcs/sources_1/ip/dem/dem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/CODWork/MCCPU_SOC/MCCPU_SOC.srcs/sources_1/ip/dem/dem.xci
# IP: The module: 'dem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CODWork/MCCPU_SOC/MCCPU_SOC.srcs/sources_1/ip/dem/dem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
