# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/CODWork/SCCPU_SOC/SCCPU_SOC.cache/wt [current_project]
set_property parent.project_path D:/CODWork/SCCPU_SOC/SCCPU_SOC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/CODWork/SCCPU_SOC/SCCPU_SOC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/CODWork/SCCPU_SOC/studentnosorting.coe
read_verilog -library xil_defaultlib {
  D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/imports/SCCPUJAL_SIM/EXT.v
  D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/imports/Desktop/MIO_BUS.v
  D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/imports/Desktop/Multi_CH32.v
  D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/imports/SCCPUJAL_SIM/ctrl_encode_def.v
  D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/imports/SCCPUJAL_SIM/NPC.v
  D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/imports/SCCPUJAL_SIM/PC.v
  D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/imports/SCCPUJAL_SIM/RF.v
  D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/imports/SCCPUJAL_SIM/alu.v
  D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/imports/Desktop/clk_div.v
  D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/imports/SCCPUJAL_SIM/ctrl.v
  D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/imports/SCCPUJAL_SIM/dm.v
  D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/imports/SCCPUJAL_SIM/mux.v
  D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/imports/SCCPUJAL_SIM/sccpu.v
  D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/imports/Desktop/seg7x16.v
  D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/imports/Desktop/SCCPU_Top.v
}
read_ip -quiet D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/ip/imem/imem.xci
set_property used_in_implementation false [get_files -all d:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/sources_1/ip/imem/imem_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/constrs_1/imports/Desktop/Nexys4DDR_CPU.xdc
set_property used_in_implementation false [get_files D:/CODWork/SCCPU_SOC/SCCPU_SOC.srcs/constrs_1/imports/Desktop/Nexys4DDR_CPU.xdc]


synth_design -top SCCPUSOC_Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SCCPUSOC_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SCCPUSOC_Top_utilization_synth.rpt -pb SCCPUSOC_Top_utilization_synth.pb"
